language: csharp
before_install:
  - sudo apt-get install nunit-console
services:
    - mysql
env:
  - CXX=g++-4.8
mono:
  - latest
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
- mysql -e "create database IF NOT EXISTS test;" -uroot
- nuget restore edge-db.sln

install:
  
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo apt-get update
  - echo "deb http://download.mono-project.com/repo/debian wheezy-apache24-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get install mono-devel
  - sudo apt-get install nunit-console
  - npm install
  - xbuild edge-db.sln
  
script:
  - nunit-console ./unit/bin/Debug/unit.dll
  
